# Generated by Django 2.0.1 on 2018-01-18 05:44

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('VIN', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2018)])),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('dimensions', django.contrib.postgres.fields.jsonb.JSONField()),
                ('weight', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
